version: "3.8"

services:
  app:
    build: .
    container_name: shinar-app
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    # Uses default ENTRYPOINT from image to run start.py